### ISSUE TITLE
npm run build doesn't work

### ISSUE THREAD

**Issue by Varunram** [josephtchung/webui#10]
`npm start` works whereas `npm run build` loads the background and doesn't seem to load the other stuff (the screen as such loads fine, but the css is messed up and the actions dont work, the screen just greys out). This may be due to a package or a library we import, so I'm not too sure how where the bug is. Once this works, packaging lit into a react app must work.

**Comment by josephtchung** [comment]
Thanks for finding this. I haven't tried npm build before, but I will figure it out!

**Comment by josephtchung** [comment]
Should be fixed now...

**Comment by Varunram** [comment]
Thank you very much, I was doing this to be able to package this into an electron app(https://github.com/mit-dci/lit/pull/252) so that we can distribute this to people and say "Hey, here's the script, you can generate an app" or something. We could even do signed binaries. I'll put in a PR with the changes here so that people can package the standalone repo as well.
